#!/bin/bash
#git recursive directories scripts - https://github.com/safrm/gr-scripts
#author: Miroslav Safr <miroslav.safr@gmail.com>
#pulls all and resets local changes in subdirectories ./ or $1/ except those which are marked by "touch <dir>/.git/no_updates"
VERSION=NA

PROJECT_DIR="$1"
if [ -z "$PROJECT_DIR" ] || [ ! -d "$PROJECT_DIR" ]; then
	PROJECT_DIR="./"
fi

CWD=`pwd`
cd $PROJECT_DIR
PROJECT_DIR=`pwd`

find ./  -type d -name ".git*"  |  sed 's/\/.git//g' | while read ENTRY
do
	if [ ! -f $ENTRY/.git/no_updates ]; then
		cd $ENTRY 
                LASTTAG=`git describe --tags --dirty=* 2> /dev/null`
		BRANCH=`git branch | egrep "^\*" | cut -d' ' -f2`
                echo -e "\033[32m $ENTRY:\033[0m \033[31m [$BRANCH] \033[0m from: \033[34m $LASTTAG \033[0m" 
		git fetch origin 
		git fetch origin --tags
		git reset --hard origin/$BRANCH
                git gc --quiet
                git pull

                TO=`git describe --tags --dirty=* 2> /dev/null`
		if [ "$LASTTAG" != "$TO" ]
		then
			echo -e " \033[33mupdated to:\033[0m \033[34m $TO \033[0m  "
			LASTMSG=`git log -1 --pretty=format:'%h %s | %ad' --date=relative`
                        echo -e "$LASTMSG"
		fi
		cd $PROJECT_DIR
	else
		echo -e "\033[32m $ENTRY:\033[0m \033[35m skipped update \033[0m" 
	fi
done

TIME=`date +%H:%M:%S`
echo "gr-pull (reset local) finished:$TIME"

