#!/bin/sh
#git recursive directories scripts - http://safrm.net/projects/gr-scripts
#author: Miroslav Safr <miroslav.safr@gmail.com>
#shows remote branches in subdirectories ./ or $1/ 
VERSION=NA                                                                   
VERSION_DATE=NA
#support color escape characters on different terminals
alias echo="/bin/echo -e"

BASENAME=`basename $0`
START_TIME=`date +'%s'`

while [ $# -gt 0 ]; do
  case "$1" in
    -ns|--no-summary) 
               NO_SUMMARY=1
               ;;
	* )        PROJECT_DIR=$1;
	       ;; 
  esac
  shift
done

if [ -z "$PROJECT_DIR" ] || [ ! -d "$PROJECT_DIR" ]; then
	PROJECT_DIR="./"
fi

if [ ! -d "$PROJECT_DIR" ] 
then
  echo "directory $PROJECT_DIR does not exist";
  exit 1
fi

CWD=`pwd`
cd $PROJECT_DIR
PROJECT_DIR=`pwd`

find "$PROJECT_DIR"  -type d -name ".git*"  |  sed 's/\/.git//g' | sort | while read ENTRY
do
		cd $ENTRY 
		#URLS=`git config --get remote.origin.url`
        URLS=`git remote -v | awk '{print $1 " " $2 }' | sort -u`  
        PROJECT20=`basename $ENTRY`
        PROJECT20=`printf '%-20s' $PROJECT20`
 		echo "\033[32m$PROJECT20\033[0m $URLS"
		cd $PROJECT_DIR
done

if [ -z "$NO_SUMMARY" ]; then
	TIME=`date +%H:%M:%S`
	ELAPSED_TIME=$((`date +'%s'` - $START_TIME))
	echo "$BASENAME finished:$TIME took:$(($ELAPSED_TIME/60)) min $(($ELAPSED_TIME%60)) s"
fi


