#!/bin/bash
#git recursive directories scripts - http://safrm.net/projects/gr-scripts
#author: Miroslav Safr <miroslav.safr@gmail.com>
#shows local tags versus current remote situation in subdirectories ./ or $1/ except those which are marked by "touch <dir>/.git/no_updates"
# -v shows the details
VERSION=NA                                                                   
VERSION_DATE=NA


while [ $# -gt 0 ]; do
  case "$1" in
    -v|--verbose) 
               VERBOSE=1
               ;;
	* )    PROJECT_DIR=$1;
	       ;; 
  esac
  shift
done

if [ -z "$PROJECT_DIR" ]
then
	PROJECT_DIR="./"
fi

if [ ! -d "$PROJECT_DIR" ] 
then
  echo "directory $PROJECT_DIR does not exist";
  exit 1
fi

CWD=`pwd`
cd $PROJECT_DIR
PROJECT_DIR=`pwd`


find ./  -type d -name ".git*"  |  sed 's/\/.git//g' | sort | while read ENTRY
do
	if [ ! -f $ENTRY/.git/no_updates ]; then
		cd $ENTRY 
                LASTTAG=`git describe --tags --dirty=* 2> /dev/null`
                echo -e "\033[32m $ENTRY:\033[0m"
		BRANCH=`git branch | egrep "^\*" | cut -d' ' -f2`
		git fetch origin 
		git fetch origin --tags

                TO=`git describe origin/master --tags 2> /dev/null`

	        LASTMSG=`git log -1 --format="%s" `
                echo -e "\033[31m [$BRANCH] \033[0m local: \033[34m $LASTTAG \033[0m remote: \033[34m $TO \033[0m ($LASTMSG)"

		if [ "$LASTTAG" == "$TO" ]
		then
			NEEDS_UPDATE=""
		else
			COMMITCOUNT=`git shortlog origin/$BRANCH..HEAD | grep -E '^[ ]+\w+' | wc -l`
			NEEDS_UPDATE=" NEEDS UPDATE OR COMMIT (+$COMMITCOUNT)"
                        echo -e "\033[33m$NEEDS_UPDATE\033[0m"
                        if [ ! -z "$VERBOSE" ]
			then
			   git status -s
			fi
		fi
		cd $PROJECT_DIR
	fi
done

TIME=`date +%H:%M:%S`
echo "`basename $0` finished:$TIME"

