'\" t
.\"     Title: gr-gr
.\"    Author: Miroslav Safr <miroslav.safr@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 20140203_1202
.\"    Manual: Git recursive directories scripts
.\"    Source: gr-scripts 1.1.0
.\"  Language: English
.\"
.TH "GR\-GR" "1" "20140203_1202" "gr-scripts 1.1.0" "Git recursive directories scri"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gr-gr \- Generic recurse script
.SH "SYNOPSIS"
.HP \w'\fBgr\-gr\ COMMAND\ [ARGUMENTS]\fR\ 'u
\fBgr\-gr COMMAND [ARGUMENTS]\fR
.SH "DESCRIPTION"
.PP
Generic recurse script, command execution wrapper\&.
.SH "COMMAND"
.PP
Command (with arguments is executed in projects containing git directories\&. Current directory is used as root directory with git clones\&.
.PP
All gr\-scipts support subdirectory hierarchy <my\-dir>/<my\-project\-group>/<git\-clone>\&.
.SH "EXAMPLES"
.PP
See sizes of cloned directories:
.sp
.if n \{\
.RS 4
.\}
.nf
         gr\-gr du \-hs
      
.fi
.if n \{\
.RE
.\}
.sp
.SH "SEE ALSO"
.PP
gr\-scripts(1)\&.
\m[blue]\fB\%http://safrm.net/projects/gr-scripts/\fR\m[]
.SH "AUTHOR"

    Miroslav Šafr <miroslav\&.safr@gmail\&.com>
  .SH "LICENSE"

   LGPL2
  .SH "AUTHOR"
.PP
\fBMiroslav Safr\fR <\&miroslav\&.safr@gmail\&.com\&>
.RS 4
Author and maintainer
.RE
