'\" t
.\"     Title: gr-initbare
.\"    Author: Miroslav Safr <miroslav.safr@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 20140203_1126
.\"    Manual: Git recursive directories scripts
.\"    Source: gr-scripts 1.1.0
.\"  Language: English
.\"
.TH "GR\-INITBARE" "1" "20140203_1126" "gr-scripts 1.1.0" "Git recursive directories scri"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gr-initbare \- Git helper to create new inited local git bare repo
.SH "SYNOPSIS"
.HP \w'\fBgr\-initbare\ [NEW_REPO_NAME]\ [OPTIONS]\ \fR\ 'u
\fBgr\-initbare [NEW_REPO_NAME] [OPTIONS] \fR [\-h,\ \-\-help] [\-d\ \-\-description\ <description>] [\-V\ \-\-version]
.SH "DESCRIPTION"
.PP
Git helper to create new inited local git bare repo with description and initial 0\&.0\&.0 tag\&. Creates bare repo <NEW_REPO_NAME> and <NEW_REPO_NAME>\-clone directories\&.
.SH "OPTIONS"
.PP
\-h \-\-help
.RS 4
Print help text to the screen\&.
.RE
.PP
\-d \-\-description <description>
.RS 4
Few words about project, otherwise is used project name\&.
.RE
.PP
\-V \-\-version
.RS 4
Prints version to the screen and exits\&.
.RE
.SH "NEW_REPO_NAME"
.PP
New git bare repo name which must not exists in current directory\&.
.SH "SEE ALSO"
.PP
gr\-scripts(1)\&.
\m[blue]\fB\%http://safrm.net/projects/gr-scripts/\fR\m[]
.SH "AUTHOR"

    Miroslav Šafr <miroslav\&.safr@gmail\&.com>
  .SH "LICENSE"

   LGPL2
  .SH "AUTHOR"
.PP
\fBMiroslav Safr\fR <\&miroslav\&.safr@gmail\&.com\&>
.RS 4
Author and maintainer
.RE
