'\" t
.\"     Title: gr-scripts
.\"    Author: Miroslav Safr <miroslav.safr@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 20140203_1126
.\"    Manual: Git recursive directories scripts
.\"    Source: gr-scripts 1.1.0
.\"  Language: English
.\"
.TH "GR\-SCRIPTS" "1" "20140203_1126" "gr-scripts 1.1.0" "Git recursive directories scri"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gr-scripts_ \- Git recursive directories scripts .PP Let monkey work to be done by monkies :) All gr\-scipts support subdirectory hierarchy <my\-dir>/<my\-project\-group>/<git\-clone>\&.
.SH "GR-SCRIPTS COMMANDS"
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
     gr\-authorcheck(1) \&.\&.\&.\&.\&. search for inappropriate commits
     gr\-branches(1) \&.\&.\&.\&.\&.\&.\&.\&. shows branches in subdirectories
     gr\-clean(1) \&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&. cleans up git clones in subdirectories
     gr\-commits2tag(1) \&.\&.\&.\&.\&. show commits from last tag divided to head,local,remote
     gr\-gr(1) \&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&. general recussive script
     gr\-initbare(1) \&.\&.\&.\&.\&.\&.\&.\&. initialize git bare repo, makes first commit and tag 0\&.0\&.0
     gr\-pull(1) \&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&. pulls all and keeps local chanegs in  subdirectories
     gr\-pullreset(1) \&.\&.\&.\&.\&.\&.\&. pulls all and resets local changes in subdirectories
     gr\-remotes(1) \&.\&.\&.\&.\&.\&.\&.\&.\&. shows remote branches in subdirectories
     gr\-show(1) \&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&. shows local tags versus current remote situation in subdirectories
     gr\-showlocal(1) \&.\&.\&.\&.\&.\&.\&. shows local tags and if it was edited in subdirectories
     gr\-tags(1) \&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&. shows tags
     
.fi
.if n \{\
.RE
.\}
.sp
.SH "EXAMPLES"
.PP
Current release contents:
.sp
.if n \{\
.RS 4
.\}
.nf
          gr\-tags <PROJ_DIR> \-v \-ns \-d 2 \-c \-hm "these changes are in last release:"
      
.fi
.if n \{\
.RE
.\}
.sp
Next release contents:
.sp
.if n \{\
.RS 4
.\}
.nf
          gr\-commits2tag <PROJ_DIR> \-or \-ns \-mc 50 \-hm "these changes will be in next release:"
      
.fi
.if n \{\
.RE
.\}
.sp
.SH "SEE ALSO"
.PP
gr\-authorcheck(8), gr\-branches(8), gr\-clean(8), gr\-commits2tag(8), gr\-gr(8) gr\-initbare(8), gr\-pull(8), gr\-pullreset(8), gr\-remotes(8), gr\-show(8), gr\-showlocal(8), gr\-tags(8)\&.
\m[blue]\fB\%http://safrm.net/projects/gr-scripts/\fR\m[]
.SH "AUTHOR"

    Miroslav Šafr <miroslav\&.safr@gmail\&.com>
  .SH "LICENSE"

   LGPL2
  .SH "AUTHOR"
.PP
\fBMiroslav Safr\fR <\&miroslav\&.safr@gmail\&.com\&>
.RS 4
Author and maintainer
.RE
